spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/splan
    username: root
    password: luonq134931

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-default-scope: luonq.mapper

logging:
  config: classpath:config/logback-spring.xml

# Massive（文档 https://massive.com/docs/rest/stocks/market-operations/market-holidays ）/ Polygon 兼容 REST
massive:
  api:
    base-url: https://api.polygon.io
    key: Ea9FNNIdlWnVnGcoTpZsOWuCWEB3JAqY